# Generated by Django 4.2.1 on 2023-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0002_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='householdHeadName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
