# Generated by Django 4.2.1 on 2023-05-11 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0003_household_householdheadname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='householdHeadName',
        ),
        migrations.AddField(
            model_name='household',
            name='houseHoldHead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangayStaff.resident'),
        ),
    ]
