# Generated by Django 4.2.1 on 2023-05-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0004_remove_household_householdheadname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
