# Generated by Django 4.2.1 on 2023-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0005_household_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('undecided', 'undecided')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
