# Generated by Django 4.2.1 on 2023-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0008_resident_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Undecided', 'Undecided')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='vaccination',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], max_length=50, null=True),
        ),
    ]
