# Generated by Django 4.2.1 on 2023-05-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0010_resident_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
