# Generated by Django 4.2.1 on 2023-05-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0011_rename_birthdate_resident_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='gender',
        ),
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
