# Generated by Django 4.2.1 on 2023-05-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0012_remove_resident_gender_alter_resident_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='status',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='vaccination',
        ),
    ]
