# Generated by Django 4.2.1 on 2023-05-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0013_remove_resident_status_remove_resident_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=50, null=True),
        ),
    ]
