# Generated by Django 4.2.1 on 2023-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0014_resident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Undecided', 'Undecided')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='vaccination',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], max_length=50, null=True),
        ),
    ]
