# Generated by Django 4.2.1 on 2023-05-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0015_resident_gender_resident_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
