# Generated by Django 4.2.1 on 2023-05-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangayStaff', '0016_alter_resident_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
